name: CI/CD for portfolio website for Minor Project
on:
  push:
     branches:["main"]
   workflow_dispatch:

jobs:
   build:
     name: Validation checks
     runs-on: ubuntu-latest

    permissions:
     pages:write
     id-token:write

steps:
   -name: checkout code
    uses: actions/checkout@v4

   -name: upload artifact
    uses: actions/upload-pages-artifact@v3
    with:
  path.

   -name:deploy to github pages
    uses: actions/deploy-pages@v4
